#!/bin/bash

HEIGHT=15
WIDTH=50
CHOICE_HEIGHT=4
TITLE="Compliant Control - Run Docker Image"
MENU="What version would you like to run?"

OPTIONS=("noetic" "ROS1: Noetic"
         "humble" "ROS2: Humble")

ROS=$(whiptail --clear \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear

if [ -z "$ROS" ]; then
    exit 1
fi

OPTIONS=("full" "full"
         "core" "core")

RUN=$(whiptail --clear \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear

if [ -z "$RUN" ]; then
    exit 1
fi

xhost +local:docker &> /dev/null

if [ $RUN = "full" ]; then
    sudo docker run -it --rm --net=host --privileged --gpus all \
        --env=NVIDIA_VISIBLE_DEVICES=all --env=NVIDIA_DRIVER_CAPABILITIES=all --env=DISPLAY --env=QT_X11_NO_MITSHM=1 \
        -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
        -v $(dirname "$0")/..:/home/dingo/compliant-control \
        compliant_control_${ROS}_${RUN} bash -c "bash;"
else
    sudo docker run -it --rm --net=host --privileged \
        -v $(dirname "$0")/..:/home/dingo/compliant-control \
        compliant_control_${ROS}_${RUN} bash -c "bash;"
fi
