#!/bin/bash
xhost +local:docker &> /dev/null

sudo docker run -it --rm --net=host --privileged --gpus all \
    --env=NVIDIA_VISIBLE_DEVICES=all --env=NVIDIA_DRIVER_CAPABILITIES=all --env=DISPLAY --env=QT_X11_NO_MITSHM=1 \
    -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
    -v $(dirname "$0")/..:/home/dingo/kinova_compliant_control \
    ros2_kinova bash -c "cd kinova_compliant_control/kinova_compliant_control; python3 main.py; bash"