/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) g_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

/* g:(i0[6])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a8, a9;
  a0=9.9999999999325395e-01;
  a1=arg[0]? arg[0][1] : 0;
  a2=sin(a1);
  a3=(a0*a2);
  a4=-8.9764977059497924e-06;
  a5=4.5303099999999999e-02;
  a6=1.1775616400000000e+00;
  a7=9.8100000000000005e+00;
  a1=cos(a1);
  a8=(a0*a1);
  a9=(a7*a8);
  a10=(a6*a9);
  a11=(a5*a10);
  a4=(a4-a11);
  a11=arg[0]? arg[0][2] : 0;
  a12=cos(a11);
  a13=-9.5022060000000005e-02;
  a14=5.9767669000000001e-01;
  a15=-7.3464102066435888e-06;
  a16=(a15*a9);
  a17=3.6034142065717501e-05;
  a16=(a16+a17);
  a17=(a14*a16);
  a18=(a13*a17);
  a19=-7.3555000000000001e-03;
  a20=-9.9999999997301536e-01;
  a21=(a20*a12);
  a22=(a21*a9);
  a23=-3.6034142066689868e-05;
  a24=7.3464102066435888e-06;
  a25=(a24*a12);
  a26=(a23*a25);
  a22=(a22+a26);
  a11=sin(a11);
  a7=(a7*a3);
  a26=(a11*a7);
  a22=(a22-a26);
  a26=(a14*a22);
  a27=(a19*a26);
  a18=(a18-a27);
  a27=arg[0]? arg[0][3] : 0;
  a28=cos(a27);
  a29=-2.3427105714285698e-03;
  a30=5.2693411999999995e-01;
  a31=-9.9999999999325395e-01;
  a32=(a31*a22);
  a33=-3.6732051036381108e-06;
  a34=(a33*a16);
  a32=(a32+a34);
  a34=(a30*a32);
  a35=(a29*a34);
  a36=8.7192069999999997e-02;
  a37=(a33*a28);
  a38=(a37*a22);
  a39=(a0*a28);
  a40=(a39*a16);
  a38=(a38+a40);
  a27=sin(a27);
  a40=(a12*a7);
  a41=(a20*a11);
  a9=(a41*a9);
  a24=(a24*a11);
  a23=(a23*a24);
  a9=(a9+a23);
  a40=(a40+a9);
  a9=(a27*a40);
  a38=(a38-a9);
  a9=(a30*a38);
  a23=(a36*a9);
  a35=(a35-a23);
  a23=arg[0]? arg[0][4] : 0;
  a42=cos(a23);
  a43=(a33*a42);
  a44=1.9583573673469402e-03;
  a45=5.8097325000000000e-01;
  a46=(a28*a40);
  a47=(a33*a27);
  a22=(a47*a22);
  a48=(a0*a27);
  a16=(a48*a16);
  a22=(a22+a16);
  a46=(a46+a22);
  a22=(a0*a46);
  a16=(a33*a32);
  a22=(a22+a16);
  a16=(a45*a22);
  a49=(a44*a16);
  a50=2.9542919326530599e-02;
  a51=(a42*a38);
  a23=sin(a23);
  a52=(a31*a23);
  a53=(a52*a32);
  a51=(a51-a53);
  a53=(a33*a23);
  a54=(a53*a46);
  a51=(a51-a54);
  a54=(a45*a51);
  a55=(a50*a54);
  a49=(a49-a55);
  a55=arg[0]? arg[0][5] : 0;
  a56=cos(a55);
  a57=(a33*a56);
  a58=7.4707836534086388e-06;
  a59=1.9776600000000003e-01;
  a60=(a43*a46);
  a38=(a23*a38);
  a61=(a31*a42);
  a32=(a61*a32);
  a38=(a38+a32);
  a60=(a60+a38);
  a38=(a31*a60);
  a32=(a33*a22);
  a38=(a38+a32);
  a38=(a59*a38);
  a32=(a58*a38);
  a62=5.4785629032461182e-02;
  a63=(a56*a51);
  a55=sin(a55);
  a64=(a0*a55);
  a65=(a64*a22);
  a63=(a63-a65);
  a65=(a33*a55);
  a66=(a65*a60);
  a63=(a63-a66);
  a63=(a59*a63);
  a66=(a62*a63);
  a32=(a32-a66);
  a66=(a57*a32);
  a67=9.7445633130940698e-07;
  a68=(a67*a63);
  a69=(a57*a60);
  a51=(a55*a51);
  a70=(a0*a56);
  a22=(a70*a22);
  a51=(a51+a22);
  a69=(a69+a51);
  a59=(a59*a69);
  a58=(a58*a59);
  a68=(a68-a58);
  a58=(a31*a68);
  a62=(a62*a59);
  a67=(a67*a38);
  a62=(a62-a67);
  a67=(a65*a62);
  a58=(a58-a67);
  a66=(a66+a58);
  a58=2.8500000000000001e-02;
  a67=(a55*a59);
  a69=(a56*a63);
  a67=(a67+a69);
  a69=(a58*a67);
  a66=(a66-a69);
  a49=(a49+a66);
  a66=(a43*a49);
  a69=-7.2220280163265302e-02;
  a51=(a69*a54);
  a45=(a45*a60);
  a44=(a44*a45);
  a51=(a51-a44);
  a44=(a70*a32);
  a60=(a33*a68);
  a22=(a64*a62);
  a60=(a60-a22);
  a44=(a44+a60);
  a60=-1.0500000000000000e-01;
  a22=(a60*a67);
  a44=(a44+a22);
  a51=(a51+a44);
  a44=(a0*a51);
  a50=(a50*a45);
  a69=(a69*a16);
  a50=(a50-a69);
  a55=(a55*a32);
  a56=(a56*a62);
  a55=(a55+a56);
  a57=(a57*a59);
  a56=(a31*a38);
  a65=(a65*a63);
  a56=(a56-a65);
  a57=(a57+a56);
  a56=(a58*a57);
  a70=(a70*a59);
  a38=(a33*a38);
  a64=(a64*a63);
  a38=(a38-a64);
  a70=(a70+a38);
  a60=(a60*a70);
  a56=(a56-a60);
  a55=(a55+a56);
  a50=(a50+a55);
  a55=(a53*a50);
  a44=(a44-a55);
  a66=(a66+a44);
  a44=1.0500000000000000e-01;
  a45=(a45+a57);
  a57=(a23*a45);
  a54=(a54+a67);
  a67=(a42*a54);
  a57=(a57+a67);
  a67=(a44*a57);
  a66=(a66-a67);
  a35=(a35+a66);
  a66=(a28*a35);
  a30=(a30*a46);
  a36=(a36*a30);
  a46=1.3087969877551000e-02;
  a67=(a46*a34);
  a36=(a36-a67);
  a23=(a23*a49);
  a42=(a42*a50);
  a23=(a23+a42);
  a43=(a43*a45);
  a16=(a16+a70);
  a0=(a0*a16);
  a53=(a53*a54);
  a0=(a0-a53);
  a43=(a43+a0);
  a44=(a44*a43);
  a45=(a61*a45);
  a16=(a33*a16);
  a54=(a52*a54);
  a16=(a16-a54);
  a45=(a45+a16);
  a16=(a58*a45);
  a44=(a44-a16);
  a23=(a23+a44);
  a36=(a36+a23);
  a23=(a27*a36);
  a66=(a66-a23);
  a23=-1.4000000000000001e-01;
  a43=(a30+a43);
  a44=(a48*a43);
  a16=(a9+a57);
  a54=(a39*a16);
  a34=(a34+a45);
  a45=(a33*a34);
  a54=(a54+a45);
  a44=(a44+a54);
  a54=(a23*a44);
  a45=2.0000000000000000e-02;
  a0=(a47*a43);
  a53=(a37*a16);
  a34=(a31*a34);
  a53=(a53+a34);
  a0=(a0+a53);
  a53=(a45*a0);
  a54=(a54-a53);
  a66=(a66+a54);
  a18=(a18+a66);
  a66=(a12*a18);
  a14=(a14*a40);
  a19=(a19*a14);
  a40=7.1723128367346903e-03;
  a54=(a40*a17);
  a19=(a19-a54);
  a47=(a47*a35);
  a37=(a37*a36);
  a46=(a46*a9);
  a29=(a29*a30);
  a46=(a46-a29);
  a61=(a61*a49);
  a49=(a33*a51);
  a52=(a52*a50);
  a49=(a49-a52);
  a61=(a61+a49);
  a58=(a58*a57);
  a61=(a61+a58);
  a46=(a46+a61);
  a31=(a31*a46);
  a37=(a37+a31);
  a47=(a47+a37);
  a28=(a28*a43);
  a27=(a27*a16);
  a28=(a28-a27);
  a45=(a45*a28);
  a47=(a47+a45);
  a19=(a19+a47);
  a47=(a11*a19);
  a66=(a66-a47);
  a47=2.8000000000000003e-01;
  a45=(a14+a28);
  a27=(a24*a45);
  a0=(a26+a0);
  a16=(a25*a0);
  a17=(a17+a44);
  a44=(a20*a17);
  a16=(a16+a44);
  a27=(a27+a16);
  a27=(a47*a27);
  a66=(a66+a27);
  a4=(a4+a66);
  a3=(a3*a4);
  a6=(a6*a7);
  a5=(a5*a6);
  a7=7.1755261309276310e-08;
  a5=(a5-a7);
  a7=(a41*a18);
  a4=(a21*a19);
  a40=(a40*a26);
  a13=(a13*a14);
  a40=(a40-a13);
  a48=(a48*a35);
  a39=(a39*a36);
  a36=(a33*a46);
  a39=(a39+a36);
  a48=(a48+a39);
  a23=(a23*a28);
  a48=(a48-a23);
  a40=(a40+a48);
  a48=(a15*a40);
  a4=(a4+a48);
  a7=(a7+a4);
  a5=(a5+a7);
  a8=(a8*a5);
  a5=-1.6910479183673500e-03;
  a5=(a5*a10);
  a7=2.1154808000000000e-01;
  a7=(a7*a6);
  a5=(a5-a7);
  a24=(a24*a18);
  a25=(a25*a19);
  a20=(a20*a40);
  a25=(a25+a20);
  a24=(a24+a25);
  a12=(a12*a45);
  a11=(a11*a0);
  a12=(a12-a11);
  a47=(a47*a12);
  a24=(a24-a47);
  a5=(a5+a24);
  a33=(a33*a5);
  a8=(a8+a33);
  a3=(a3+a8);
  a8=-2.9999999999999999e-02;
  a6=(a6+a12);
  a1=(a1*a6);
  a41=(a41*a45);
  a21=(a21*a0);
  a15=(a15*a17);
  a21=(a21+a15);
  a41=(a41+a21);
  a10=(a10+a41);
  a2=(a2*a10);
  a1=(a1-a2);
  a8=(a8*a1);
  a3=(a3-a8);
  if (res[0]!=0) res[0][0]=a3;
  if (res[0]!=0) res[0][1]=a5;
  if (res[0]!=0) res[0][2]=a40;
  if (res[0]!=0) res[0][3]=a46;
  if (res[0]!=0) res[0][4]=a51;
  if (res[0]!=0) res[0][5]=a68;
  return 0;
}

CASADI_SYMBOL_EXPORT int g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int g_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
